apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "connector.fullname" . | trunc 41 }}-drop-chunk
  labels:
    app: {{ template "connector.fullname" . }}
    chart: {{ template "connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.dropChunk.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-drop-chunk
            image: postgres:12-alpine
            args:
            - psql
            {{- if .Values.connection.dbURI.secretTemplate }}
            - $(PROMSCALE_DB_URI)
            {{- end }}
            - -c
            - CALL prom_api.execute_maintenance();
            env:
              {{- if not .Values.connection.dbURI.secretTemplate }}
              - name: PGPORT
                value: {{ .Values.connection.port | quote }}
              - name: PGUSER
                value: {{ .Values.connection.user }}
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ tpl .Values.connection.password.secretTemplate . }}
                    key: {{ .Values.connection.user }}
              - name: PGHOST
                value: {{ tpl .Values.connection.host.nameTemplate . }}
              - name:  PGDATABASE
                value: {{ .Values.connection.dbName }}
              {{- else }}
              - name: PROMSCALE_DB_URI
                valueFrom:
                  secretKeyRef:
                    name: {{ tpl .Values.connection.dbURI.secretTemplate . }}
                    key: {{ .Values.connection.dbURI.name }}
              {{- end }}
          restartPolicy: OnFailure
